### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by stuarthayhurst**
- Adds an installation section
 - Documents workaround for GNOME Shell unable to fetch album art from a URL
 - Make 'Technical details' section consistent in formatting with the rest of the README

### CODE REVIEW

**Comment by stuarthayhurst** [comment]
I recommend adding the command-line work-around to the extension's description on extensions.gnome.org too, to avoid more bug-reports from users that didn't read the README.

**Comment by wjt** [comment]
Would you like to adopt this extension? I don't actually use it any more.

**Comment by stuarthayhurst** [comment]
Sure, I use the extension so I don't mind maintaining it :)
I don't completely know how it works with changing ownership on GNOME's extensions website, I think you can request it on their [Matrix channel](https://gnome.element.io/#/room/#extensions:gnome.org). Or I can just publish it under a new UUID, but users would have to manually switch extensions.

**Comment by wjt** [comment]
Ok, extension listing transferred to you. If you rename/delete your fork of the repo I can transfer this one to you. (I tried but GitHub won't let me transfer the repo when you already have one of the same name.) Or I can just archive. Let me know!

**Comment by stuarthayhurst** [comment]
Deleted my fork, I'm good for it to be transferred when you get a chance, thanks :)

**Pull request merged**
